# SPDX-License-Identifier: GPL-2.0

sunh5-drm-y			+=	sunh5_drv.o
sunh5-drm-y			+=	sunh5_framebuffer.o
	
sunh5-mixer-y		+=	sunh5_mixer.o
sunh5-mixer-y		+=	sunh5_vi_layer.o
sunh5-mixer-y		+=	sunh5_vi_scaler.o
sunh5-mixer-y		+=	sunh5_ui_layer.o
sunh5-mixer-y		+=	sunh5_ui_scaler.o
sunh5-mixer-y		+=	sunh5_csc.o

sunh5-tcon-y		+= sunh5_tcon.o
sunh5-tcon-y		+= sunh5_crtc.o

sunh5-drm-hdmi-y	+= sunh5_dw_hdmi.o
sunh5-drm-hdmi-y	+= sunh5_hdmi_phy.o
sunh5-drm-hdmi-y	+= sunh5_hdmi_phy_clk.o

obj-y				+=	sunh5-drm.o
obj-y				+=	sunh5-mixer.o
obj-y				+=	sunh5-tcon.o
obj-y				+=	sunh5-drm-hdmi.o