obj-y +=	ion.o ion-ioctl.o ion_heap.o \
			ion_page_pool.o ion_system_heap.o \
			ion_carveout_heap.o ion_chunk_heap.o ion_cma_heap.o \
			ion_of.o
ifdef CONFIG_COMPAT
obj-y += compat_ion.o
endif
obj-y += sunxi/